language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  - PINS="mirage:https://github.com/yomimono/mirage.git#icmp_type mirage-types:https://github.com/yomimono/mirage.git#icmp_type"
  matrix:
  - OCAML_VERSION=4.02 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=tcpip MIRAGE_MODE=xen
