language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
  matrix:
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.05 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.05 PACKAGE=tcpip MIRAGE_MODE=hvt
  - OCAML_VERSION=4.06 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.07 PACKAGE=tcpip MIRAGE_MODE=qubes
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.07 PACKAGE=tcpip MIRAGE_MODE=virtio
